// frontend/src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import { Navbar } from './components/Navbar'
import { LeaderboardPage } from './pages/LeaderboardPage'
import { ChannelDetailPage } from './pages/ChannelDetailPage'

export default function App() {
  return (
    <BrowserRouter>
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <Routes>
          <Route path="/" element={<LeaderboardPage />} />
          <Route path="/channel/:channelId" element={<ChannelDetailPage />} />
        </Routes>
      </div>
    </BrowserRouter>
  )
}

// frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { NavbarComponent } from './components/navbar/navbar.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, NavbarComponent],
  template: `
    <div class="min-h-screen bg-gray-50">
      <app-navbar />
      <router-outlet />
    </div>
  `,
})
export class AppComponent {}
