// frontend/src/components/ReturnBadge.tsx
interface Props {
  value: number | null | undefined
  suffix?: string
}

export function ReturnBadge({ value, suffix = '%' }: Props) {
  if (value == null) {
    return <span className="text-gray-400 text-sm">—</span>
  }

  const pct = (value * 100).toFixed(2)
  const positive = value >= 0

  return (
    <span
      className={`inline-flex items-center gap-0.5 font-mono text-sm font-semibold ${
        positive ? 'text-success-600' : 'text-danger-600'
      }`}
    >
      {positive ? '+' : ''}
      {pct}
      {suffix}
    </span>
  )
}

// frontend/src/app/components/return-badge/return-badge.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-return-badge',
  standalone: true,
  imports: [],
  template: `
    @if (value() == null) {
      <span class="text-gray-400 text-sm">—</span>
    } @else {
      <span
        class="inline-flex items-center gap-0.5 font-mono text-sm font-semibold"
        [class.text-success-600]="value()! >= 0"
        [class.text-danger-600]="value()! < 0"
      >
        {{ value()! >= 0 ? '+' : '' }}{{ (value()! * 100).toFixed(2) }}{{ suffix() }}
      </span>
    }
  `,
})
export class ReturnBadgeComponent {
  readonly value = input<number | null | undefined>(null);
  readonly suffix = input('%');
}
